version: '3.8'

services:
  maximize:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maximize
    ports:
      - "8081:8081"
    volumes:
      # Persist token storage
      - maximize-tokens:/app/.maximize
      # Optional: mount custom config ONLY if it exists
      # Comment out this line if you don't have a config.json file
      # - ./config.json:/app/config.json:ro
    environment:
      - PORT=8081
      - BIND_ADDRESS=0.0.0.0
      - LOG_LEVEL=info
      - TOKEN_FILE=/app/.maximize/tokens.json
    restart: unless-stopped
    # Required for interactive CLI authentication
    stdin_open: true
    tty: true
    networks:
      - maximize-network

volumes:
  maximize-tokens:
    driver: local

networks:
  maximize-network:
    driver: bridge
