version: '3.8'

services:
  maximize:
    build: .
    ports:
      - "8081:8081"
    environment:
      # Set these with your actual tokens
      - MAXIMIZE_AUTHENTICATION_CODE=${MAXIMIZE_AUTHENTICATION_CODE:-}
      - MAXIMIZE_ACCESS_TOKEN=${MAXIMIZE_ACCESS_TOKEN:-}
      - MAXIMIZE_REFRESH_TOKEN=${MAXIMIZE_REFRESH_TOKEN:-}
      - MAXIMIZE_API_KEY=${MAXIMIZE_API_KEY:-}
      - MAXIMIZE_TOKEN_EXPIRES_IN=86400
      # Debug mode
      - RUST_LOG=info
      - RUST_BACKTRACE=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/healthz"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
